---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: pr-spring-helm-1
  namespace: argocd
spec:
  destination:
    namespace: pr-spring-helm-1
    server: https://kubernetes.default.svc
  project: previews
  source:
    helm:
      values: |
        image:
          tag: "f3c5736"
        ingress:
          host: pr-spring-helm-1.35.197.205.55.xip.io
      version: v3
    path: helm
    repoURL: https://github.com/sguisado/spring-helm
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
